// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509040217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("backend.Models.Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Occupations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "โปรแกรมเมอร์"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ดีไซน์เนอร์"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ครู"
                        },
                        new
                        {
                            Id = 4,
                            Name = "หมอ"
                        },
                        new
                        {
                            Id = 5,
                            Name = "วิศวกร"
                        },
                        new
                        {
                            Id = 6,
                            Name = "นักบัญชี"
                        },
                        new
                        {
                            Id = 7,
                            Name = "นักการตลาด"
                        },
                        new
                        {
                            Id = 8,
                            Name = "นักเขียน"
                        },
                        new
                        {
                            Id = 9,
                            Name = "นักวิทยาศาสตร์"
                        },
                        new
                        {
                            Id = 10,
                            Name = "นักกฎหมาย"
                        });
                });

            modelBuilder.Entity("backend.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileBase64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("backend.Models.ProfileOccupation", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OccupationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId", "OccupationId");

                    b.HasIndex("OccupationId");

                    b.ToTable("ProfileOccupations");
                });

            modelBuilder.Entity("backend.Models.ProfileOccupation", b =>
                {
                    b.HasOne("backend.Models.Occupation", "Occupation")
                        .WithMany("ProfileOccupations")
                        .HasForeignKey("OccupationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Profile", "Profile")
                        .WithMany("ProfileOccupations")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Occupation");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("backend.Models.Occupation", b =>
                {
                    b.Navigation("ProfileOccupations");
                });

            modelBuilder.Entity("backend.Models.Profile", b =>
                {
                    b.Navigation("ProfileOccupations");
                });
#pragma warning restore 612, 618
        }
    }
}
